"""Tests for Markdown renderer."""

from meeting_note.compile.markdown import _escape_cell, _status_label, render_markdown
from meeting_note.models import AgendaStatus, MeetingNote


class TestRenderMarkdown:
    def test_minimal_meeting(self) -> None:
        note = MeetingNote(title="Minimal Meeting", date="2026-04-07T10:00:00+09:00")
        md = render_markdown(note)
        assert "# Minimal Meeting" in md
        assert "2026-04-07" in md

    def test_full_meeting(self, sample_meeting_note: MeetingNote) -> None:
        md = render_markdown(sample_meeting_note)
        assert "# Sprint Planning Meeting" in md
        assert "## Participants" in md
        assert "Tanaka" in md
        assert "## Participant Dynamics" in md
        assert "## Agenda" in md
        assert "## Key Takeaways" in md

    def test_decided_agenda_has_decisions(self, sample_meeting_note: MeetingNote) -> None:
        md = render_markdown(sample_meeting_note)
        assert "#### Decisions" in md
        assert "**Why**:" in md
        assert "Alternatives considered" in md
        assert "~~Full rewrite~~" in md
        assert "Decided by" in md

    def test_pending_agenda_has_unresolved(self, sample_meeting_note: MeetingNote) -> None:
        md = render_markdown(sample_meeting_note)
        assert "#### Unresolved" in md
        assert "Budget approval" in md
        assert "[PENDING]" in md

    def test_action_items_table(self, sample_meeting_note: MeetingNote) -> None:
        md = render_markdown(sample_meeting_note)
        assert "#### Action Items" in md
        assert "| Owner | Task | Due | Context |" in md
        assert "Suzuki" in md
        assert "2026-04-14" in md

    def test_participant_dynamics_table(self, sample_meeting_note: MeetingNote) -> None:
        md = render_markdown(sample_meeting_note)
        assert "| From | To | Relation | Topic | Detail |" in md
        assert "proposal_approval" in md

    def test_key_takeaways_rendered(self, sample_meeting_note: MeetingNote) -> None:
        md = render_markdown(sample_meeting_note)
        assert "- API redesign will proceed" in md

    def test_duration_rendered(self, sample_meeting_note: MeetingNote) -> None:
        md = render_markdown(sample_meeting_note)
        assert "60 min" in md

    def test_metadata_footer(self, sample_meeting_note: MeetingNote) -> None:
        md = render_markdown(sample_meeting_note)
        assert "Generated by" in md


class TestEscapeCell:
    def test_pipe_escaped(self) -> None:
        assert _escape_cell("a | b") == "a \\| b"

    def test_newline_escaped(self) -> None:
        assert _escape_cell("line1\nline2") == "line1<br>line2"


class TestStatusLabel:
    def test_decided(self) -> None:
        assert _status_label(AgendaStatus.DECIDED) == "[DECIDED]"

    def test_pending(self) -> None:
        assert _status_label(AgendaStatus.PENDING) == "[PENDING]"

    def test_rejected(self) -> None:
        assert _status_label(AgendaStatus.REJECTED) == "[REJECTED]"

    def test_informational(self) -> None:
        assert _status_label(AgendaStatus.INFORMATIONAL) == "[INFO]"
